Algoritmo "Exercicio do terreno Exemplo 2"

Var
   largura, comprimento, metroQuadrado, area, preco : real
   

Inicio
 escreva ("Largura do terreno ")
 leia (largura)
 escreva("Comprimento do terreno ")
 leia (comprimento)
 escreva ("valor do metro quadrado ")
 leia (metroQuadrado)
 
  area <- largura * comprimento
  preco <- area * metroQuadrado
  
  escreval ("Area do terreno = ", area:8:2)
  escreval ("Preco do terreno = ", preco:8:2)
  




Fimalgoritmo